# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Catalina Margozzini
email: camargozzini@gmail.com
description: "Creo que el potencial democratizador de información de la tecnología e Internet es enorme, por eso dedico mi trabajo a intenar que la comunicación persona-computador sea lo más fluida posible."
baseurl: "http://camargozzini.com/" # the subpath of your site, e.g. /blog
url: "http://camargozzini.com/" # the base hostname & protocol for your site
twitter_username: camargozzini
github_username:  camargozzini

# Build settings
markdown: kramdown

prose:
  ignore: ['favicon.ico','about.html','js']
  siteurl: 'http://camargozzini.com'
