# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cata Margozzini
email: info@ciudadanointeligente.org
description: "Creo que el diseño de información en conjunto con las tecnologías de información son la forma de democratizar los contenidos, empoderar la ciudadanía y cambiar el mundo. Por eso diseño y escribo código (abierto)."
baseurl: "http://semaforoelectoral.cl/" # the subpath of your site, e.g. /blog
url: "http://semaforoelectoral.cl" # the base hostname & protocol for your site
twitter_username: ciudadanoi
github_username:  ciudadanointeligente

# Build settings
markdown: kramdown
