# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Catalina Margozzini
email: camargozzini@gmail.com
description: "I am a Chilean UX and digital designer (and coder). My passion to observe behaviors and empathizing with people makes me good at detecting problems and finding solutions."
baseurl: "http://camargozzini.com/" # the subpath of your site, e.g. /blog
url: "http://camargozzini.com/" # the base hostname & protocol for your site
twitter_username: camargozzini
github_username:  camargozzini

# Build settings
markdown: kramdown

prose:
  ignore: ['favicon.ico','about.html','js']
  siteurl: 'http://camargozzini.com'
  metadata:
    _posts:
      - name: description
        field:
          element: 'textarea'
          label: 'descripcion'
